### ISSUE TITLE
No longer required recaptcha_ajax.js

### ISSUE THREAD

**Issue by RayDCDA** [Cyber-Duck/SilverStripe-Recaptcha#2]
It seems the recaptcha_ajax.js is no longer required and removed by Google, can you remove `Requirements::javascript('https://www.google.com/recaptcha/api/js/recaptcha_ajax.js');` 
from CyberDuck\Recaptcha\Forms\RecaptchaField, as it is throwing a javascript error for 404 not found and MIME type miss match?

**Comment by samthejarvis** [comment]
Fixed in #3

**Comment by samthejarvis** [comment]
Fixed in #3
